apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http