apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/LauraOkafor/eks-gitops-monitoring.git
    targetRevision: main
    path: argocd-apps/taskflow/base
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
