apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: default
spec:
  chart:
    spec:
      chart: ./helm-charts/backend
      sourceRef:
        kind: GitRepository
        name: taskflow-repo
        namespace: argocd
  values:
    image:
      repository: lauraokafor/backend
      tag: latest