apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: monitoring
spec:
  chart:
    spec:
      chart: ./helm-charts/backend
      sourceRef:
        kind: GitRepository
        name: taskflow-repo
        namespace: monitoring
  values:
    image:
      repository: lauraokafor/fullstack
      tag: backend